const numberButtons = document.querySelectorAll('.numbers')
const operationButtons = document.querySelectorAll('.operators')
const equalsButton = document.querySelector('.equals')
const deleteButton = document.querySelector('.delete')
const resetButton = document.querySelector('.reset')
const previousText = document.querySelector('.previous-js')
const currentText = document.querySelector('.current-js')
